var cadeno = 'RamonLover4Ever';
var numerologi = 23;
var bote = false;
var carlo = true;
;
var arr = ['elbicho', 16, true];
var atmuez = ['bof', false, 23];
console.log(cadeno, numerologi, bote, carlo, arr, atmuez);
var babalu = 'matarile';
console.log(babalu);
